[package]
name = "json"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
flatten-json-object = "0.6.1"
json-objects-to-csv = "0.1.3"
polars = { version = "0.43.1", features = ["lazy", "regex", "strings"] }
serde_json = "1.0.132"
